name: update xkcd

on:
  workflow_dispatch:
  schedule:
  - cron: "4 20 * * *"

jobs:
  update-xkcd:
    runs-on: ubuntu-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0

    - name: replace xkcd
      run: ./xkcd.sh

    - name: add and commit
      uses: EndBug/add-and-commit@v9
      with:
        add: 'README.md'
        author_name: Joshua Jeschek
        committer_name: Github Actions
        message: 'Update xkcd comic'
